#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* conv_3d_buf = 
"/*\n"
"*Native 3D convolution kernel for MNN's OpenCL buffer backend.\n"
" *\n"
"*Replaces the GeometryConv3D fallback that decomposes Conv3D into\n"
"*~40 Conv2D+Im2Col+Unpack+Transpose ops per layer,producing\n"
"*the ~3300-kernel-launch fan-out that makes SIAM-class 3D U-Nets\n"
"*kernel-launch-bound on real GPUs.\n"
" *\n"
"*Data layout\n"
"*-----------\n"
"*Input/output use MNN's standard OpenCL buffer layout for 5D\n"
"*tensors: `[Cblock,N,D,H,W,4]` where Cblock=ceil(C/4) and\n"
"*the trailing 4 is the channel-pack. For batch=1 (always true for\n"
"*sliding-window inference):\n"
" *\n"
"*offset_voxel=(cblock*D+d)*H+h)*W+w // float4\n"
"*pixel=vload4(offset_voxel,base)\n"
" *\n"
"*Weights are repacked at session creation into a kernel-friendly\n"
"*layout that the host's Conv3DBufExecution writes:\n"
" *\n"
"*[Cout_block,Kd,Kh,Kw,Cin_block,4_cin,4_cout] // 16 floats\n"
" *\n"
"*For each (cout_block,kd,kh,kw,cin_block) tile,the kernel\n"
"*loads 4 input channels via vload4,dot-products them against a\n"
"*4x4 weight slab,and accumulates into a 4-channel output vector.\n"
" *\n"
"*Bias layout is plain [Cout_block*4] floats; we vload4 a\n"
"*Cout-aligned chunk per work-item.\n"
" *\n"
"*SIAM Conv3D shape set covered by this single kernel:\n"
" *\n"
"*kernel 1x1x1 stride (1,1,1) pad (0,0,0)\n"
"*kernel 3x3x3 stride (1,1,1) pad (1,1,1)\n"
"*kernel 3x3x3 stride (2,2,2) pad (1,1,1)\n"
"*kernel 3x3x3 stride (2,2,1) pad (1,1,1)\n"
" *\n"
"*All group=1,dilation=1. No relu/relu6 fusion (SIAM uses\n"
"*InstanceNorm+LeakyReLU as separate ops between Conv3D blocks).\n"
" */\n"
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0, "" __private const int global_size_dim1, "" __private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(d0, d1, d2) "" if (d0 >= global_size_dim0 || "" d1 >= global_size_dim1 || "" d2 >= global_size_dim2) { "" return; "" }\n"
"/*\n"
"*conv_3d_buf_nc4dhw4\n"
" *\n"
"*Global work size:\n"
"*dim0 : out_w\n"
"*dim1 : out_d*out_h\n"
"*dim2 : out_cblock (= ceil(Cout/4)) -- batch=1 baked in\n"
" *\n"
"*Each work-item produces one float4 of output (4 consecutive output\n"
"*channels at one DHW voxel).\n"
" */\n"
"__kernel void conv_3d_buf_nc4dhw4(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_cblock,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0);\n"
" const int gid_dh=get_global_id(1);\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ox=gid_w;\n"
" const int oh=gid_dh % out_h;\n"
" const int od=gid_dh/out_h;\n"
" const int oc_blk=gid_cb;\n"
" /* Accumulator: 4 consecutive output channels at (od,oh,ox). */\n"
" COMPUTE_FLOAT4 acc=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" /* Receptive-field corner in the input volume. */\n"
" const int in_d_base=od*sd-pd;\n"
" const int in_h_base=oh*sh-ph;\n"
" const int in_w_base=ox*sw-pw;\n"
" /* Weight base offset for this oc_blk:\n"
"*[oc_blk,kd,kh,kw,ic_blk,4_cin,4_cout]\n"
"*Per (kd,kh,kw,ic_blk) tile=16 floats=4 float4. */\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz=in_d_base+kdi;\n"
" if (idz<0 || idz >= in_d) {\n"
" continue;\n"
" }\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy=in_h_base+khi;\n"
" if (idy<0 || idy >= in_h) {\n"
" continue;\n"
" }\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx=in_w_base+kwi;\n"
" if (idx<0 || idx >= in_w) {\n"
" continue;\n"
" }\n"
" /* Weight base for THIS (kdi,khi,kwi) at this oc_blk:\n"
"*step over (ic_blk,4_cin,4_cout) inner tiles. */\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" /* Loop over input-channel blocks. Each iteration:\n"
"*load 4 input channels (vload4)+16 weights (4 cin x 4 cout)\n"
"*accumulate 4 MADs into the 4-channel accumulator. */\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" /* Input layout: [cblock,batch=1,D,H,W,4]\n"
"*offset_voxel=(ic_blk*D+idz)*H*W+idy*W+idx\n"
"*(we treat batch=1 implicitly; the lower bits of\n"
"*the offset are inside the C/4 block). */\n"
" const int in_voxel=((ic_blk*in_d+idz)*in_h+idy)*in_w+idx;\n"
" COMPUTE_FLOAT4 in_v=CONVERT_COMPUTE_FLOAT4(vload4(in_voxel,input));\n"
" /* Weights for this (oc_blk,kdi,khi,kwi,ic_blk).\n"
"*4 float4s=16 floats total. Each float4 is the\n"
"*4 cout values for a single cin lane. */\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.x),w0,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.y),w1,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.z),w2,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.w),w3,acc);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" /* Output: same NC4DHW4 layout as input. */\n"
" const int out_voxel=((oc_blk*out_d+od)*out_h+oh)*out_w+ox;\n"
" vstore4(CONVERT_FLOAT4(acc),out_voxel,output);\n"
"}\n"
"/*\n"
"*conv_3d_buf_nchw_in\n"
" *\n"
"*Variant that reads its INPUT as plain unpacked NCHW (1,C,D*H*W)\n"
"*instead of NC4HW4-packed. Used when the Conv3D input is a\n"
"*MEMORY_VIRTUAL tensor with an identity-stride Region pointing at an\n"
"*NCHW-formatted upstream tensor (MNN's BUFFER backend stores NCHW\n"
"*tensors as unpacked [N*C*H*W] floats). Consuming the upstream\n"
"*NCHW buffer directly lets us skip the Raster materialization step\n"
"*MNN would otherwise schedule -- removing one huge (Cin*D*H*W*4)\n"
"*intermediate buffer per Conv3D op.\n"
" *\n"
"*OUTPUT is still NC4DHW4 packed (matches the Conv3D output tensor's\n"
"*declared format=NC4HW4).\n"
" *\n"
"*Cin is passed exactly (not rounded to multiple-of-4); the inner\n"
"*loop reads `Cin` consecutive channels for each (kd,kh,kw) tile,\n"
"*4-per-iteration where possible,with a single-channel fallback for\n"
"*the leftover at the end.\n"
" *\n"
"*Layout maps:\n"
"*input[c,d,h,w]=input[c*(in_d*in_h*in_w)+d*in_h*in_w+h*in_w+w]\n"
" */\n"
"__kernel void conv_3d_buf_nchw_in(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_c,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0);\n"
" const int gid_dh=get_global_id(1);\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ox=gid_w;\n"
" const int oh=gid_dh % out_h;\n"
" const int od=gid_dh/out_h;\n"
" const int oc_blk=gid_cb;\n"
" COMPUTE_FLOAT4 acc=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" const int in_d_base=od*sd-pd;\n"
" const int in_h_base=oh*sh-ph;\n"
" const int in_w_base=ox*sw-pw;\n"
" /* in_cblock=number of 4-cin tiles,including a possibly-padded\n"
"*tail block when in_c is not a multiple of 4. */\n"
" const int in_cblock=(in_c+3) >> 2;\n"
" const int in_spatial=in_d*in_h*in_w;\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz=in_d_base+kdi;\n"
" if (idz<0 || idz >= in_d) continue;\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy=in_h_base+khi;\n"
" if (idy<0 || idy >= in_h) continue;\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx=in_w_base+kwi;\n"
" if (idx<0 || idx >= in_w) continue;\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" const int spat_off=(idz*in_h+idy)*in_w+idx;\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" const int c_base=ic_blk*4;\n"
" /* Read 4 channels (strided by in_spatial). The\n"
"*tail block reads zeros for c >= in_c. */\n"
" COMPUTE_FLOAT in_x=(c_base+0<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+0)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_y=(c_base+1<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+1)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_z=(c_base+2<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+2)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_w_= (c_base+3<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+3)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" acc=mad((COMPUTE_FLOAT4)(in_x),w0,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_y),w1,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_z),w2,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_w_),w3,acc);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" const int out_voxel=((oc_blk*out_d+od)*out_h+oh)*out_w+ox;\n"
" vstore4(CONVERT_FLOAT4(acc),out_voxel,output);\n"
"}\n"
;
#endif
}
