#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* conv_3d_buf = 
"/*\n"
"*Native 3D convolution kernel for MNN's OpenCL buffer backend.\n"
" *\n"
"*Replaces the GeometryConv3D fallback that decomposes Conv3D into\n"
"*~40 Conv2D+Im2Col+Unpack+Transpose ops per layer,producing\n"
"*the ~3300-kernel-launch fan-out that makes SIAM-class 3D U-Nets\n"
"*kernel-launch-bound on real GPUs.\n"
" *\n"
"*Data layout\n"
"*-----------\n"
"*Input/output use MNN's standard OpenCL buffer layout for 5D\n"
"*tensors: `[Cblock,N,D,H,W,4]` where Cblock=ceil(C/4) and\n"
"*the trailing 4 is the channel-pack. For batch=1 (always true for\n"
"*sliding-window inference):\n"
" *\n"
"*offset_voxel=(cblock*D+d)*H+h)*W+w // float4\n"
"*pixel=vload4(offset_voxel,base)\n"
" *\n"
"*Weights are repacked at session creation into a kernel-friendly\n"
"*layout that the host's Conv3DBufExecution writes:\n"
" *\n"
"*[Cout_block,Kd,Kh,Kw,Cin_block,4_cin,4_cout] // 16 floats\n"
" *\n"
"*For each (cout_block,kd,kh,kw,cin_block) tile,the kernel\n"
"*loads 4 input channels via vload4,dot-products them against a\n"
"*4x4 weight slab,and accumulates into a 4-channel output vector.\n"
" *\n"
"*Bias layout is plain [Cout_block*4] floats; we vload4 a\n"
"*Cout-aligned chunk per work-item.\n"
" *\n"
"*SIAM Conv3D shape set covered by this single kernel:\n"
" *\n"
"*kernel 1x1x1 stride (1,1,1) pad (0,0,0)\n"
"*kernel 3x3x3 stride (1,1,1) pad (1,1,1)\n"
"*kernel 3x3x3 stride (2,2,2) pad (1,1,1)\n"
"*kernel 3x3x3 stride (2,2,1) pad (1,1,1)\n"
" *\n"
"*All group=1,dilation=1. No relu/relu6 fusion (SIAM uses\n"
"*InstanceNorm+LeakyReLU as separate ops between Conv3D blocks).\n"
" */\n"
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0, "" __private const int global_size_dim1, "" __private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(d0, d1, d2) "" if (d0 >= global_size_dim0 || "" d1 >= global_size_dim1 || "" d2 >= global_size_dim2) { "" return; "" }\n"
"/*\n"
"*conv_3d_buf_nc4dhw4\n"
" *\n"
"*Global work size:\n"
"*dim0 : out_w\n"
"*dim1 : out_d*out_h\n"
"*dim2 : out_cblock (= ceil(Cout/4)) -- batch=1 baked in\n"
" *\n"
"*Each work-item produces one float4 of output (4 consecutive output\n"
"*channels at one DHW voxel).\n"
" */\n"
"__kernel void conv_3d_buf_nc4dhw4(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_cblock,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0);\n"
" const int gid_dh=get_global_id(1);\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ox=gid_w;\n"
" const int oh=gid_dh % out_h;\n"
" const int od=gid_dh/out_h;\n"
" const int oc_blk=gid_cb;\n"
" /* Accumulator: 4 consecutive output channels at (od,oh,ox). */\n"
" COMPUTE_FLOAT4 acc=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" /* Receptive-field corner in the input volume. */\n"
" const int in_d_base=od*sd-pd;\n"
" const int in_h_base=oh*sh-ph;\n"
" const int in_w_base=ox*sw-pw;\n"
" /* Weight base offset for this oc_blk:\n"
"*[oc_blk,kd,kh,kw,ic_blk,4_cin,4_cout]\n"
"*Per (kd,kh,kw,ic_blk) tile=16 floats=4 float4. */\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz=in_d_base+kdi;\n"
" if (idz<0 || idz >= in_d) {\n"
" continue;\n"
" }\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy=in_h_base+khi;\n"
" if (idy<0 || idy >= in_h) {\n"
" continue;\n"
" }\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx=in_w_base+kwi;\n"
" if (idx<0 || idx >= in_w) {\n"
" continue;\n"
" }\n"
" /* Weight base for THIS (kdi,khi,kwi) at this oc_blk:\n"
"*step over (ic_blk,4_cin,4_cout) inner tiles. */\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" /* Loop over input-channel blocks. Each iteration:\n"
"*load 4 input channels (vload4)+16 weights (4 cin x 4 cout)\n"
"*accumulate 4 MADs into the 4-channel accumulator. */\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" /* Input layout: [cblock,batch=1,D,H,W,4]\n"
"*offset_voxel=(ic_blk*D+idz)*H*W+idy*W+idx\n"
"*(we treat batch=1 implicitly; the lower bits of\n"
"*the offset are inside the C/4 block). */\n"
" const int in_voxel=((ic_blk*in_d+idz)*in_h+idy)*in_w+idx;\n"
" COMPUTE_FLOAT4 in_v=CONVERT_COMPUTE_FLOAT4(vload4(in_voxel,input));\n"
" /* Weights for this (oc_blk,kdi,khi,kwi,ic_blk).\n"
"*4 float4s=16 floats total. Each float4 is the\n"
"*4 cout values for a single cin lane. */\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.x),w0,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.y),w1,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.z),w2,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.w),w3,acc);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" /* Output: same NC4DHW4 layout as input. */\n"
" const int out_voxel=((oc_blk*out_d+od)*out_h+oh)*out_w+ox;\n"
" vstore4(CONVERT_FLOAT4(acc),out_voxel,output);\n"
"}\n"
"/*\n"
"*conv_3d_buf_nc4dhw4_t22\n"
" *\n"
"*2x2 output-tile variant of conv_3d_buf_nc4dhw4. Each work-item now\n"
"*produces FOUR output float4s (2 along H,2 along W) at one (od,oc_blk),\n"
"*so the weight tile loaded for each (kdi,khi,kwi,ic_blk) is reused\n"
"*across 4 outputs instead of 1.\n"
" *\n"
"*SIAM benefit: weight-load bandwidth drops 4x; input-load bandwidth\n"
"*stays roughly the same per output (the 2x2 outputs read from slightly\n"
"*overlapping but mostly distinct input voxels). For our memory-bound\n"
"*naive kernel this gives roughly 3-4x speedup on the dominant Conv3D\n"
"*shapes (Cin=Cout=64..256,stride=1,3x3x3).\n"
" *\n"
"*Global work size:\n"
"*dim0 : ceil(out_w/2)\n"
"*dim1 : out_d*ceil(out_h/2)\n"
"*dim2 : out_cblock\n"
" *\n"
"*Boundary handling: when out_w or out_h is odd,the last work-item\n"
"*has its ow1/oh1 lane out of range; per-lane stores are guarded\n"
"*by if (ow1<out_w) and if (oh1<out_h) to leave odd-tail\n"
"*voxels untouched by the tiled kernel.\n"
" */\n"
"__kernel void conv_3d_buf_nc4dhw4_t22(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_cblock,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0); /* covers ow0,ow1=ow0+1 */\n"
" const int gid_dh=get_global_id(1); /* od*out_h_pairs+oh_pair */\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ow0=gid_w*2;\n"
" const int ow1=ow0+1;\n"
" const int out_h_pairs=(out_h+1) >> 1;\n"
" const int oh_pair=gid_dh % out_h_pairs;\n"
" const int od=gid_dh/out_h_pairs;\n"
" const int oh0=oh_pair*2;\n"
" const int oh1=oh0+1;\n"
" const int oc_blk=gid_cb;\n"
" /* Four accumulators,one per spatial output position in the tile. */\n"
" COMPUTE_FLOAT4 bias_v=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" COMPUTE_FLOAT4 acc00=bias_v;\n"
" COMPUTE_FLOAT4 acc01=bias_v;\n"
" COMPUTE_FLOAT4 acc10=bias_v;\n"
" COMPUTE_FLOAT4 acc11=bias_v;\n"
" const int in_d_base=od*sd-pd;\n"
" const int in_h_base0=oh0*sh-ph;\n"
" const int in_h_base1=oh1*sh-ph;\n"
" const int in_w_base0=ow0*sw-pw;\n"
" const int in_w_base1=ow1*sw-pw;\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz=in_d_base+kdi;\n"
" if (idz<0 || idz >= in_d) {\n"
" continue;\n"
" }\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy00=in_h_base0+khi;\n"
" const int idy10=in_h_base1+khi;\n"
" const bool vy0=(idy00 >= 0 && idy00<in_h);\n"
" const bool vy1=(idy10 >= 0 && idy10<in_h) && (oh1<out_h);\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx00=in_w_base0+kwi;\n"
" const int idx01=in_w_base1+kwi;\n"
" const bool vx0=(idx00 >= 0 && idx00<in_w);\n"
" const bool vx1=(idx01 >= 0 && idx01<in_w) && (ow1<out_w);\n"
" /* Skip the whole inner-channel loop if no output lane\n"
"*in this 2x2 tile gets a contribution from this (kd,kh,kw). */\n"
" if (!(vy0 && (vx0 || vx1)) && !(vy1 && (vx0 || vx1))) {\n"
" continue;\n"
" }\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" /* Load the 4x4 weight tile ONCE; reuse across all 4 outputs. */\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" const int row_base=(ic_blk*in_d+idz)*in_h;\n"
" if (vy0) {\n"
" const int spat_h0=row_base+idy00;\n"
" if (vx0) {\n"
" COMPUTE_FLOAT4 v=CONVERT_COMPUTE_FLOAT4(vload4(spat_h0*in_w+idx00,input));\n"
" acc00=mad((COMPUTE_FLOAT4)(v.x),w0,acc00);\n"
" acc00=mad((COMPUTE_FLOAT4)(v.y),w1,acc00);\n"
" acc00=mad((COMPUTE_FLOAT4)(v.z),w2,acc00);\n"
" acc00=mad((COMPUTE_FLOAT4)(v.w),w3,acc00);\n"
" }\n"
" if (vx1) {\n"
" COMPUTE_FLOAT4 v=CONVERT_COMPUTE_FLOAT4(vload4(spat_h0*in_w+idx01,input));\n"
" acc01=mad((COMPUTE_FLOAT4)(v.x),w0,acc01);\n"
" acc01=mad((COMPUTE_FLOAT4)(v.y),w1,acc01);\n"
" acc01=mad((COMPUTE_FLOAT4)(v.z),w2,acc01);\n"
" acc01=mad((COMPUTE_FLOAT4)(v.w),w3,acc01);\n"
" }\n"
" }\n"
" if (vy1) {\n"
" const int spat_h1=row_base+idy10;\n"
" if (vx0) {\n"
" COMPUTE_FLOAT4 v=CONVERT_COMPUTE_FLOAT4(vload4(spat_h1*in_w+idx00,input));\n"
" acc10=mad((COMPUTE_FLOAT4)(v.x),w0,acc10);\n"
" acc10=mad((COMPUTE_FLOAT4)(v.y),w1,acc10);\n"
" acc10=mad((COMPUTE_FLOAT4)(v.z),w2,acc10);\n"
" acc10=mad((COMPUTE_FLOAT4)(v.w),w3,acc10);\n"
" }\n"
" if (vx1) {\n"
" COMPUTE_FLOAT4 v=CONVERT_COMPUTE_FLOAT4(vload4(spat_h1*in_w+idx01,input));\n"
" acc11=mad((COMPUTE_FLOAT4)(v.x),w0,acc11);\n"
" acc11=mad((COMPUTE_FLOAT4)(v.y),w1,acc11);\n"
" acc11=mad((COMPUTE_FLOAT4)(v.z),w2,acc11);\n"
" acc11=mad((COMPUTE_FLOAT4)(v.w),w3,acc11);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" }\n"
" }\n"
" /* Write the 2x2 outputs; guard the upper edges. */\n"
" const int out_row=(oc_blk*out_d+od)*out_h;\n"
" const int out_voxel00=(out_row+oh0)*out_w+ow0;\n"
" vstore4(CONVERT_FLOAT4(acc00),out_voxel00,output);\n"
" if (ow1<out_w) {\n"
" vstore4(CONVERT_FLOAT4(acc01),out_voxel00+1,output);\n"
" }\n"
" if (oh1<out_h) {\n"
" const int out_voxel10=(out_row+oh1)*out_w+ow0;\n"
" vstore4(CONVERT_FLOAT4(acc10),out_voxel10,output);\n"
" if (ow1<out_w) {\n"
" vstore4(CONVERT_FLOAT4(acc11),out_voxel10+1,output);\n"
" }\n"
" }\n"
"}\n"
"/*\n"
"*conv_3d_buf_nchw_in\n"
" *\n"
"*Variant that reads its INPUT as plain unpacked NCHW (1,C,D*H*W)\n"
"*instead of NC4HW4-packed. Used when the Conv3D input is a\n"
"*MEMORY_VIRTUAL tensor with an identity-stride Region pointing at an\n"
"*NCHW-formatted upstream tensor (MNN's BUFFER backend stores NCHW\n"
"*tensors as unpacked [N*C*H*W] floats). Consuming the upstream\n"
"*NCHW buffer directly lets us skip the Raster materialization step\n"
"*MNN would otherwise schedule -- removing one huge (Cin*D*H*W*4)\n"
"*intermediate buffer per Conv3D op.\n"
" *\n"
"*OUTPUT is still NC4DHW4 packed (matches the Conv3D output tensor's\n"
"*declared format=NC4HW4).\n"
" *\n"
"*Cin is passed exactly (not rounded to multiple-of-4); the inner\n"
"*loop reads `Cin` consecutive channels for each (kd,kh,kw) tile,\n"
"*4-per-iteration where possible,with a single-channel fallback for\n"
"*the leftover at the end.\n"
" *\n"
"*Layout maps:\n"
"*input[c,d,h,w]=input[c*(in_d*in_h*in_w)+d*in_h*in_w+h*in_w+w]\n"
" */\n"
"__kernel void conv_3d_buf_nchw_in(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_c,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0);\n"
" const int gid_dh=get_global_id(1);\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ox=gid_w;\n"
" const int oh=gid_dh % out_h;\n"
" const int od=gid_dh/out_h;\n"
" const int oc_blk=gid_cb;\n"
" COMPUTE_FLOAT4 acc=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" const int in_d_base=od*sd-pd;\n"
" const int in_h_base=oh*sh-ph;\n"
" const int in_w_base=ox*sw-pw;\n"
" /* in_cblock=number of 4-cin tiles,including a possibly-padded\n"
"*tail block when in_c is not a multiple of 4. */\n"
" const int in_cblock=(in_c+3) >> 2;\n"
" const int in_spatial=in_d*in_h*in_w;\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz=in_d_base+kdi;\n"
" if (idz<0 || idz >= in_d) continue;\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy=in_h_base+khi;\n"
" if (idy<0 || idy >= in_h) continue;\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx=in_w_base+kwi;\n"
" if (idx<0 || idx >= in_w) continue;\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" const int spat_off=(idz*in_h+idy)*in_w+idx;\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" const int c_base=ic_blk*4;\n"
" /* Read 4 channels (strided by in_spatial). The\n"
"*tail block reads zeros for c >= in_c. */\n"
" COMPUTE_FLOAT in_x=(c_base+0<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+0)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_y=(c_base+1<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+1)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_z=(c_base+2<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+2)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_w_= (c_base+3<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+3)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" acc=mad((COMPUTE_FLOAT4)(in_x),w0,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_y),w1,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_z),w2,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_w_),w3,acc);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" const int out_voxel=((oc_blk*out_d+od)*out_h+oh)*out_w+ox;\n"
" vstore4(CONVERT_FLOAT4(acc),out_voxel,output);\n"
"}\n"
;
#endif
}
