#include "opencl_source_map.hpp" 
namespace MNN { 
#ifndef MNN_OPENCL_BUFFER_CLOSED
const char* deconv_3d_buf = 
"/*\n"
"*Native 3D transposed convolution kernel for MNN's OpenCL buffer\n"
"*backend.\n"
" *\n"
"*Replaces the GeometryConvTranspose3D fallback that decomposes\n"
"*ConvTranspose3D into MatMul+Col2Im+Reduce+Bias-Add+Activate\n"
"*via a virtual (1,batch*oc*kd*kh*kw,batch*oc*od*oh*ow) tensor.\n"
"*At SIAM v0.3 decoder scale (oc=256,k=3,od*oh*ow ~= 9216) the\n"
"*intermediate Reduce kernel either silently zeros or kernel-faults\n"
"*on NVIDIA OpenCL,blocking the 5 post-Concat decoder Conv3D ops.\n"
" *\n"
"*Algorithm: GATHER formulation.\n"
" *\n"
"*For each output voxel (od,oh,ow) and each 4-output-channel\n"
"*block,accumulate contributions from input voxels that map onto\n"
"*this output position through the ConvTranspose3D math:\n"
" *\n"
"*od=id*sd-pd+kd => id=(od+pd-kd)/sd\n"
" *\n"
"*`id` is valid only when (od+pd-kd) is divisible by sd AND\n"
"*0 <= id<in_d. Same for h and w axes. Voxels added by the ONNX\n"
"*output_padding extension naturally produce bias-only outputs\n"
"*because no (id,kd) pair maps to them.\n"
" *\n"
"*Data layout: identical to conv_3d_buf -- input/output use MNN's\n"
"*NC4DHW4 packed layout [Cblock,N,D,H,W,4]; weights pack into\n"
"*[Cout_block,Kd,Kh,Kw,Cin_block,4_cin,4_cout] (the host\n"
"*Deconv3DBufExecution.cpp transforms ONNX's (Cin,Cout,Kd,Kh,Kw)\n"
"*into this kernel-friendly layout at session-init time).\n"
" *\n"
"*SIAM ConvTranspose3D shape set covered by this kernel:\n"
" *\n"
"*kernel 3x3x3 stride (2,2,2) pad (1,1,1) output_pad (1,1,1)\n"
" *\n"
"*(6 ops total; channel pairs 320->320 x2,320->256,256->128,\n"
"*128->64,64->32.)\n"
" *\n"
"*Group=1,dilation=1 only (SIAM does not exercise other variants).\n"
" */\n"
"#ifdef MNN_SUPPORT_FP16\n"
"#pragma OPENCL EXTENSION cl_khr_fp16 : enable\n"
"#endif\n"
"#define GLOBAL_SIZE_3_DIMS "" __private const int global_size_dim0, "" __private const int global_size_dim1, "" __private const int global_size_dim2,\n"
"#define DEAL_NON_UNIFORM_DIM3(d0, d1, d2) "" if (d0 >= global_size_dim0 || "" d1 >= global_size_dim1 || "" d2 >= global_size_dim2) { "" return; "" }\n"
"/*\n"
"*deconv_3d_buf_nc4dhw4\n"
" *\n"
"*Global work size:\n"
"*dim0 : out_w\n"
"*dim1 : out_d*out_h\n"
"*dim2 : out_cblock (= ceil(Cout/4)) -- batch=1 baked in\n"
" *\n"
"*Each work-item produces one float4 of output (4 consecutive output\n"
"*channels at one DHW voxel).\n"
" */\n"
"__kernel void deconv_3d_buf_nc4dhw4(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_cblock,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0);\n"
" const int gid_dh=get_global_id(1);\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ox=gid_w;\n"
" const int oh=gid_dh % out_h;\n"
" const int od=gid_dh/out_h;\n"
" const int oc_blk=gid_cb;\n"
" COMPUTE_FLOAT4 acc=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" /* Weight base offset for this oc_blk -- same packing as conv_3d_buf:\n"
"*[oc_blk,kd,kh,kw,ic_blk,4_cin,4_cout] 16 floats per tile. */\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz_num=od+pd-kdi;\n"
" if (idz_num<0) {\n"
" continue;\n"
" }\n"
" if ((idz_num % sd) != 0) {\n"
" continue;\n"
" }\n"
" const int idz=idz_num/sd;\n"
" if (idz >= in_d) {\n"
" continue;\n"
" }\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy_num=oh+ph-khi;\n"
" if (idy_num<0) {\n"
" continue;\n"
" }\n"
" if ((idy_num % sh) != 0) {\n"
" continue;\n"
" }\n"
" const int idy=idy_num/sh;\n"
" if (idy >= in_h) {\n"
" continue;\n"
" }\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx_num=ox+pw-kwi;\n"
" if (idx_num<0) {\n"
" continue;\n"
" }\n"
" if ((idx_num % sw) != 0) {\n"
" continue;\n"
" }\n"
" const int idx=idx_num/sw;\n"
" if (idx >= in_w) {\n"
" continue;\n"
" }\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" /* Input layout: [cblock,batch=1,D,H,W,4] */\n"
" const int in_voxel=((ic_blk*in_d+idz)*in_h+idy)*in_w+idx;\n"
" COMPUTE_FLOAT4 in_v=CONVERT_COMPUTE_FLOAT4(vload4(in_voxel,input));\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.x),w0,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.y),w1,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.z),w2,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_v.w),w3,acc);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" const int out_voxel=((oc_blk*out_d+od)*out_h+oh)*out_w+ox;\n"
" vstore4(CONVERT_FLOAT4(acc),out_voxel,output);\n"
"}\n"
"/*\n"
"*deconv_3d_buf_nchw\n"
" *\n"
"*Variant for tensors that flow through a ConvertTensor (NC4HW4 -> NCHW)\n"
"*before the ConvTranspose3D op. The actual buffer contains 5D NCDHW\n"
"*data: input[c,d,h,w]=input[c*D*H*W+d*H*W+h*W+w].\n"
" *\n"
"*SIAM's decoder uses this path: every ConvTranspose3D in the network\n"
"*has a preceding ConvertTensor that materializes its input into NCHW\n"
"*layout (so that the downstream Concat can see matching layouts from\n"
"*both the deconv branch and the skip branch). Output stays NCHW too\n"
"*for the Concat to consume directly.\n"
" *\n"
"*Each work-item still produces 4 output channels at one DHW voxel,\n"
"*but reads/writes are scalar (strided) loads/stores instead of\n"
"*vload4/vstore4. Weights stay in the same packed kernel-friendly\n"
"*layout the host builds.\n"
" */\n"
"__kernel void deconv_3d_buf_nchw(GLOBAL_SIZE_3_DIMS\n"
" __global const FLOAT *input,\n"
" __global const FLOAT *weight,\n"
" __global const FLOAT *bias,\n"
" __global FLOAT *output,\n"
" __private const int in_c,\n"
" __private const int in_d,\n"
" __private const int in_h,\n"
" __private const int in_w,\n"
" __private const int out_c,\n"
" __private const int out_d,\n"
" __private const int out_h,\n"
" __private const int out_w,\n"
" __private const int kd,\n"
" __private const int kh,\n"
" __private const int kw,\n"
" __private const int sd,\n"
" __private const int sh,\n"
" __private const int sw,\n"
" __private const int pd,\n"
" __private const int ph,\n"
" __private const int pw) {\n"
" const int gid_w=get_global_id(0);\n"
" const int gid_dh=get_global_id(1);\n"
" const int gid_cb=get_global_id(2);\n"
" DEAL_NON_UNIFORM_DIM3(gid_w,gid_dh,gid_cb);\n"
" const int ox=gid_w;\n"
" const int oh=gid_dh % out_h;\n"
" const int od=gid_dh/out_h;\n"
" const int oc_blk=gid_cb;\n"
" const int oc0=oc_blk*4;\n"
" COMPUTE_FLOAT4 acc=CONVERT_COMPUTE_FLOAT4(vload4(oc_blk,bias));\n"
" const int in_cblock=(in_c+3) >> 2;\n"
" const int in_spatial=in_d*in_h*in_w;\n"
" const int w_kvol=kd*kh*kw;\n"
" const int w_per_oc=w_kvol*in_cblock*4*4;\n"
" const int w_oc_base=oc_blk*w_per_oc;\n"
" for (int kdi=0; kdi<kd; ++kdi) {\n"
" const int idz_num=od+pd-kdi;\n"
" if (idz_num<0) continue;\n"
" if ((idz_num % sd) != 0) continue;\n"
" const int idz=idz_num/sd;\n"
" if (idz >= in_d) continue;\n"
" for (int khi=0; khi<kh; ++khi) {\n"
" const int idy_num=oh+ph-khi;\n"
" if (idy_num<0) continue;\n"
" if ((idy_num % sh) != 0) continue;\n"
" const int idy=idy_num/sh;\n"
" if (idy >= in_h) continue;\n"
" for (int kwi=0; kwi<kw; ++kwi) {\n"
" const int idx_num=ox+pw-kwi;\n"
" if (idx_num<0) continue;\n"
" if ((idx_num % sw) != 0) continue;\n"
" const int idx=idx_num/sw;\n"
" if (idx >= in_w) continue;\n"
" const int w_kpos_base=w_oc_base\n"
"+((kdi*kh+khi)*kw+kwi)*in_cblock*16;\n"
" const int spat_off=(idz*in_h+idy)*in_w+idx;\n"
" for (int ic_blk=0; ic_blk<in_cblock; ++ic_blk) {\n"
" const int c_base=ic_blk*4;\n"
" /* Read 4 input channels (strided by in_spatial),zero-pad\n"
"*channels past in_c so the inner loop runs to completion\n"
"*without boundary branches. */\n"
" COMPUTE_FLOAT in_x=(c_base+0<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+0)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_y=(c_base+1<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+1)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_z=(c_base+2<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+2)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" COMPUTE_FLOAT in_w_= (c_base+3<in_c) ? CONVERT_COMPUTE_FLOAT(input[(c_base+3)*in_spatial+spat_off]) : (COMPUTE_FLOAT)0.0f;\n"
" const int w_offset=w_kpos_base+ic_blk*16;\n"
" COMPUTE_FLOAT4 w0=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset));\n"
" COMPUTE_FLOAT4 w1=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+4));\n"
" COMPUTE_FLOAT4 w2=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+8));\n"
" COMPUTE_FLOAT4 w3=CONVERT_COMPUTE_FLOAT4(vload4(0,weight+w_offset+12));\n"
" acc=mad((COMPUTE_FLOAT4)(in_x),w0,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_y),w1,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_z),w2,acc);\n"
" acc=mad((COMPUTE_FLOAT4)(in_w_),w3,acc);\n"
" }\n"
" }\n"
" }\n"
" }\n"
" /* NCHW write: scalar stores at strided channel offsets. */\n"
" const int out_spatial=out_d*out_h*out_w;\n"
" const int out_spat_off=(od*out_h+oh)*out_w+ox;\n"
" if (oc0+0<out_c) output[(oc0+0)*out_spatial+out_spat_off]=CONVERT_FLOAT(acc.x);\n"
" if (oc0+1<out_c) output[(oc0+1)*out_spatial+out_spat_off]=CONVERT_FLOAT(acc.y);\n"
" if (oc0+2<out_c) output[(oc0+2)*out_spatial+out_spat_off]=CONVERT_FLOAT(acc.z);\n"
" if (oc0+3<out_c) output[(oc0+3)*out_spatial+out_spat_off]=CONVERT_FLOAT(acc.w);\n"
"}\n"
;
#endif
}
